export const SelecteCtegorias = [
    { "nombre": "Asignación de Espacios Físicos y Publicación de Salones", "display": false },
    { "nombre": "Cierre académico", "display": true },
    { "nombre": "Cierre formativo", "display": true },
    { "nombre": "Comité de idiomas", "display": true },
    { "nombre": "Contratación profesores/as cátedra", "display": false },
    { "nombre": "Evaluación integral de profesores", "display": false },
    { "nombre": "English Area", "display": true },
    { "nombre": "Homologaciones, reconocimientos y validaciones", "display": true },
    { "nombre": "Incentivos y reconocimientos profesores", "display": false },
    { "nombre": "Inicio y finalización de clases", "display": true },
    { "nombre": "Modificaciones curriculares", "display": false },
    { "nombre": "Otras actividades de la vida universitaria", "display": true },
    { "nombre": "Pago de matrículas", "display": true },
    { "nombre": "Plan de trabajo del profesor/a", "display": false },
    { "nombre": "Proceso de inducción", "display": true },
    { "nombre": "Proceso de Planeación y Oferta Académica", "display": false },
    { "nombre": "Publicación de grupos cancelados", "display": true },
    { "nombre": "Recesos y vacaciones", "display": true },
    { "nombre": "Retiro de asignaturas", "display": true },
    { "nombre": "Reporte de calificaciones", "display": true },
    { "nombre": "Reserva de cupo, re activaciones de cupo y reintegros", "display": true },
    { "nombre": "Registro de asignaturas", "display": true },
]