export const Programa = [
    "Administración de Empresas",
    "Administración de Negocios Internacionales",
    "Administración en Logística y Producción",
    "Antropología",
    "Arquitectura",
    "Artes",
    "Artes Liberales en Ciencias Sociales",
    "Biología",
    "Ciencia Política y Gobierno",
    "Creación",
    "Diseño",
    "Doctorado en Ciencias Biomédicas y Biológicas",
    "Doctorado en Ciencias de la Dirección",
    "Doctorado en Derecho",
    "Doctorado en Economía",
    "Doctorado en Estudios Políticos e Internacionales",
    "Doctorado en Investigación Clínica",
    "Economía",
    "Especialización en Traducción",
    "Especialización En Contratación Estatal Y Su Gestión",
    "Especialización En Derecho Aduanero y Comercio Exterior",
    "Especialización En Derecho Internacional",
    "Especialización En Gerencia Pública Y Control Fiscal",
    "Especialización en Anestesia Cardiotorácica",
    "Especialización en Anestesiología",
    "Especialización en Cardiología",
    "Especialización en Cardiología Intervencionista y Hemodinamia",
    "Especialización en Cardiología Pediátrica",
    "Especialización en Cirugía Cardiovascular",
    "Especialización en Cirugía General",
    "Especialización en Cirugía Vascular Periférica y Angiología",
    "Especialización en Cirugía de Mano",
    "Especialización en Coloproctología",
    "Especialización en Contratación Estatal y su Gestión",
    "Especialización en Cuidado Intensivo Pediátrico",
    "Especialización en Derecho Administrativo",
    "Especialización en Derecho Administrativo",
    "Especialización en Derecho Administrativo",
    "Especialización en Derecho Aduanero y del Comercio Exterior",
    "Especialización en Derecho Ambiental",
    "Especialización en Derecho Ambiental",
    "Especialización en Derecho Comercial",
    "Especialización en Derecho Comercial",
    "Especialización en Derecho Constitucional",
    "Especialización en Derecho Constitucional",
    "Especialización en Derecho Contractual",
    "Especialización en Derecho Contractual",
    "Especialización en Derecho Empresarial y de los Negocios",
    "Especialización en Derecho Financiero",
    "Especialización en Derecho Internacional",
    "Especialización en Derecho Internacional de Los Derechos Humanos y Derecho Internacional Humanitario",
    "Especialización en Derecho Laboral y de La Seguridad Social",
    "Especialización en Derecho Laboral y de La Seguridad Social",
    "Especialización en Derecho Laboral y de la Seguridad Social",
    "Especialización en Derecho Médico Sanitario",
    "Especialización en Derecho Médico Sanitario",
    "Especialización en Derecho Penal",
    "Especialización en Derecho Probatorio",
    "Especialización en Derecho Procesal",
    "Especialización en Derecho Procesal",
    "Especialización en Derecho Procesal",
    "Especialización en Derecho Tributario",
    "Especialización en Derecho Tributario",
    "Especialización en Derecho Urbano",
    "Especialización en Derecho Urbano",
    "Especialización en Derecho Urbano",
    "Especialización en Derecho de Familia",
    "Especialización en Derecho de Hidrocarburos",
    "Especialización en Derecho de Seguros",
    "Especialización en Derecho de la Empresa",
    "Especialización en Derecho del Mar",
    "Especialización en Ecocardiografía",
    "Especialización en Educación para Profesionales de la Salud",
    "Especialización en Ejercicio Físico para La Salud",
    "Especialización en Endocrinología",
    "Especialización en Evaluación y Desarrollo de Proyectos",
    "Especialización en Evaluación y Desarrollo de Proyectos",
    "Especialización en Finanzas",
    "Especialización en Finanzas",
    "Especialización en Fisioterapia en Paciente Adulto Crítico",
    "Especialización en Gastroenterología y Endoscopia Digestiva",
    "Especialización en Gerencia Integral de Servicios de Salud",
    "Especialización en Gerencia Integral de Servicios de Salud - Virtual",
    "Especialización en Gerencia Pública y Control Fiscal",
    "Especialización en Gerencia de Empresas",
    "Especialización en Gerencia de Empresas",
    "Especialización en Gerencia de Empresas",
    "Especialización en Gerencia de Marketing para entornos digitales",
    "Especialización en Gerencia de Mercadeo",
    "Especialización en Gerencia de Mercadeo",
    "Especialización en Gerencia de Mercadeo",
    "Especialización en Gerencia de Negocios Globales",
    "Especialización en Gerencia de Negocios Internacionales",
    "Especialización en Gerencia de Proyectos de Construcción e Infraestructura",
    "Especialización en Gerencia de Proyectos de Construcción e Infraestructura",
    "Especialización en Gerencia de Proyectos de Construcción e Infraestructura",
    "Especialización en Gerencia de Proyectos de Construcción e Infraestructura",
    "Especialización en Gerencia de Proyectos de Construcción e Infraestructura",
    "Especialización en Gerencia de Proyectos de Servicios con Tic",
    "Especialización en Gerencia de Proyectos de Servicios con Tic",
    "Especialización en Gerencia y Gestión Cultural",
    "Especialización en Gerencia y Gestión Cultural",
    "Especialización en Gestión Humana",
    "Especialización en Gestión Humana",
    "Especialización en Gestión Humana",
    "Especialización en Gestión Humana",
    "Especialización en Ginecología y Obstetricia",
    "Especialización en Infectología",
    "Especialización en Mastología",
    "Especialización en Medicina Crítica y Cuidado Intensivo",
    "Especialización en Medicina Interna",
    "Especialización en Medicina Materno Fetal",
    "Especialización en Medicina Nuclear",
    "Especialización en Medicina de Emergencias",
    "Especialización en Medicina del Dolor y Cuidado Paliativo",
    "Especialización en Mercado de Capitales",
    "Especialización en Nefrología",
    "Especialización en Neonatología",
    "Especialización en Neurocirugía",
    "Especialización en Neurofisiología Clínica",
    "Especialización en Neurología",
    "Especialización en Oftalmología",
    "Especialización en Ortopedia y Traumatología",
    "Especialización en Otorrinolaringología",
    "Especialización en Pediatría",
    "Especialización en Perfusión y Circulación Extracorpórea",
    "Especialización en Propiedad Intelectual",
    "Especialización en Psiquiatría",
    "Especialización en Radiología",
    "Especialización en Rehabilitación Cardiaca y Pulmonar",
    "Especialización en Retina y Vítreo",
    "Especialización en Salud Ocupacional",
    "Especialización en Toxicología Clínica",
    "Especialización en Urología",
    "Filosofía",
    "Finanzas y Comercio Internacional",
    "Fisioterapia",
    "Fonoaudiología",
    "Gestión y Desarrollo Urbanos",
    "Historia",
    "Ingeniería Biomédica",
    "Ingeniería Electrónica",
    "Ingeniería Industrial",
    "Jurisprudencia",
    "Licenciatura en Ciencias Sociales",
    "Licenciatura en Filosofía",
    "Maestría en Actividad Física y Salud",
    "Maestría en Actividad Física y Salud",
    "Maestría en Administración - MBA",
    "Maestría en Administración en Salud",
    "Maestría en Ciencias Naturales",
    "Maestría en Ciencias de la Rehabilitación",
    "Maestría en Conflicto, Memoria y Paz",
    "Maestría en Derecho",
    "Maestría en Derecho Administrativo",
    "Maestría en Derecho Internacional",
    "Maestría en Derecho laboral y de la Seguridad Social",
    "Maestría en Derecho y Gestión Ambiental",
    "Maestría en Derecho y Gestión Urbanística",
    "Maestría en Dirección",
    "Maestría en Economía",
    "Maestría en Economía de las Políticas Públicas",
    "Maestría en Educación para Profesionales de la Salud",
    "Maestría en Emprendimiento e Innovación",
    "Maestría en Estudios Políticos e Internacionales",
    "Maestría en Estudios Sociales",
    "Maestría en Filosofía",
    "Maestría en Finanzas",
    "Maestría en Finanzas Cuantitativas",
    "Maestría en Ingeniería Biomédica",
    "Maestría en Marketing",
    "Maestría en Periodismo",
    "Maestría en Salud Pública",
    "Maestría en Seguridad y Salud en el Trabajo",
    "Maestría en Seguridad y Salud en el Trabajo",
    "Marketing y Negocios Digitales",
    "Matemáticas Aplicadas y Ciencias de la Computación",
    "Medicina",
    "Periodismo y Opinión Pública",
    "Psicología",
    "Relaciones Internacionales",
    "Sociología",
    "Teatro Musical",
    "Terapia Ocupacional"
] 